# my global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'cadvisor'
    scrape_interval: 5s

    static_configs:
      - targets: ['cadvisor:9080']

  - job_name: 'node-exporter'
    scrape_interval: 5s

    static_configs:
      - targets: ['node-exporter:9100']
